USE ads_app;

CREATE TABLE Users(
UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserName VARCHAR   (50) NOT NULL,
Email VARCHAR   (50) NOT NULL,
Password VARCHAR   (50) NOT NULL,
    CONSTRAINT uc_UserName UNIQUE (UserName),
    CONSTRAINT uc_Email UNIQUE (Email) 
);

CREATE TABLE Ads(
AdsID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserID_ INTEGER NOT NULL,
CategoryID_ INTEGER NOT NULL,
AdsName VARCHAR(50) NOT NULL,
AdsPrice VARCHAR(50) NOT NULL,
AdsDescription TEXT ,
AdsPhotoPaths TEXT NOT NULL,
FOREIGN KEY (UserID_) REFERENCES Users (UserID)
);
  
CREATE TABLE Profils (
ProfilID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
Age INTEGER NOT NULL,
Gender VARCHAR(8) ,
PPurl TEXT ,
Number INTEGER  NOT NULL,
    CONSTRAINT uc_Number UNIQUE (Number)

);

CREATE TABLE UserAdsFavorite(
FavoriteID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserID_ INTEGER NOT NULL,
AdsID_ INTEGER NOT NULL,
FOREIGN KEY (UserID_) REFERENCES Users (UserID),
FOREIGN KEY (AdsID_) REFERENCES Ads (AdsID)
);

CREATE TABLE Photos(
PhotoID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Url TEXT NOT NULL,
AdsID_ INTEGER NOT NULL,
FOREIGN KEY (AdsID_) REFERENCES Ads (AdsID)
);

CREATE TABLE Category(
CategoryID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CategoryName TEXT NOT NULL,
CategoryPhotoUrl TEXT NOT NULL
);


ALTER TABLE Ads  
ADD FOREIGN KEY (CategoryID_) REFERENCES Category (CategoryID);

ALTER TABLE Ads  
ADD isSelled BIT ;

ALTER TABLE Profils 
ADD UserID_ INTEGER,
ADD FOREIGN KEY (UserID_) REFERENCES Users (UserID);

ALTER TABLE Ads 
ADD ProfilID_ INTEGER,
ADD FOREIGN KEY (ProfilID_) REFERENCES Profils (ProfilID);

ALTER TABLE UserAdsFavorite 
ADD isFavorite BIT ;

ALTER TABLE Ads
MODIFY COLUMN AdsPrice INT;
